language: go
go: 1.2
before_install:
  - go get code.google.com/p/go.tools/cmd/vet
  - go get github.com/golang/lint/golint
install:
  - go get -d -v -t ./...
script:
  - go vet ./...
  - $HOME/gopath/bin/golint **/*.go
  - LINTED=$($HOME/gopath/bin/golint **/*.go| wc -l); if [ $LINTED -gt 0 ]; then echo "golint - $LINTED statements not up to spec, please run golint and follow the suggestions." && exit 1; fi
after_script:
  - FIXED=$(go fmt ./... | wc -l); if [ $FIXED -gt 0 ]; then echo "gofmt - $FIXED file(s) not formatted correctly, please run gofmt to fix this." && exit 1; fi
